name: Build Pocketbase AMD64
on:
  pull_request:
    branches:
      - production
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Build Pocketbase AMD64 and Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Container Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: docker.io/${{ vars.DOCKERHUB_USERNAME }}/pocketbase
          tags: |
            type=raw,value=${{ vars.PB_VERSION }}
            type=raw,value=latest
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            PB_VERSION=${{ vars.PB_VERSION }}
