name: Build Pocketbase
on:
  pull_request:
    branches:
      - production
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Build Pocketbase and Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Container Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
        images: docker.io/${{ vars.DOCKERHUB_USERNAME }}/pocketbase
          tags: |
            type=raw,value=latest
            type=raw,value=build-${{ github.run_number }}
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ github.sha }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          push: true
